### ISSUE TITLE
Use of minimumPointsPerCluster in the algorithm and epsilon

### ISSUE THREAD

**Issue by AmraniRiyad** [viceroypenguin/DBSCAN#2]
Hi,

While using your library to find points cluster on an image I might have found two problems:
- First with minimumPointsPerCluster:
https://github.com/viceroypenguin/DBSCAN/blob/ec12b7fe55a7557270a10b7f5f5e08dab2c1aa1f/DBSCAN/DBSCAN.cs#L41-L52
Here you do the first scan to get the nearest candidates from the current point. But you are already using `if (candidates.Count >= minimumPointsPerCluster)` while the cluster might not be complete already.

For example on this image i have 30 points spaced by 20px : 
With `espsilon = 21` and `minimumPointsPerCluster = 10` I find 0 clusters. When I should be finding my cluster with 30 points.
<img src="https://user-images.githubusercontent.com/9655024/101139157-6adacc00-3611-11eb-8452-5a587b7014be.png" width="500">

- Another issue is with Epsilon
https://github.com/viceroypenguin/DBSCAN/blob/ec12b7fe55a7557270a10b7f5f5e08dab2c1aa1f/DBSCAN/ListSpatialIndex.cs#L36
I think you should be using `<=` because on my example i wont find any points with epsilon = 20 while my points spacing is 20. So i endedup using epsilon = 21.

**Comment by viceroypenguin** [comment]
Thanks for your interest in the library. 

* With regards to minimumPointsPerCluster, the code is correct as written. Please see the algorithm document [here](https://en.wikipedia.org/wiki/DBSCAN), where it notes that minimumPointsPerCluster is used to identify the _initial_ points. The DBSCAN would not identify any clusters in your image unless you used minimumPointsPerCluster = 2 or epsilon = 29 (20 * √2). 

* With regards to epsilon, when dealing w/ floating point numbers, equality is rarely something that's worth checking. For your case, I would generally recommend using 20.01 or similar to address. However, if you wish to change it to `<=`, then please submit a PR and I will be happy to pull it in.

**Comment by AmraniRiyad** [comment]
Thank you for the clarification ! 

I think I will end up using my own algorithm, it takes 1 second for 3000 points, but I don't think I will have to go over the 10000 points use case.

**Comment by viceroypenguin** [comment]
Great! Glad to be of assistance.
